// Generated by CoffeeScript 1.6.3
(function() {
  var M, Main, U, global;

  global = this;

  Main = (function() {
    function Main() {
      U.phello();
      this.initCss();
      return;
    }

    Main.prototype.initCss = function() {};

    return Main;

  })();

  global.Util = {
    phello: function() {
      return console.log("hello");
    },
    randomInt: function(n) {
      return M.floor(M.random() * n);
    },
    generateRandomColor255: function(chroma) {
      var color_elem;
      if (chroma == null) {
        chroma = 255;
      }
      color_elem = [255, 255 - chroma, U.randomInt(255)].shuffle();
      return {
        r: color_elem[0],
        g: color_elem[1],
        b: color_elem[2]
      };
    }
  };

  Array.prototype.shuffle = function() {
    var buf;
    buf = [];
    while (this.length > 0) {
      buf.push(this.splice(U.randomInt(this.length), 1)[0]);
    }
    while (buf.length > 0) {
      this.push(buf.pop());
    }
    return this;
  };

  M = Math;

  U = Util;

  $(function() {
    return global.main = new Main;
  });

}).call(this);
