// Generated by CoffeeScript 1.6.3
(function() {
  var M, Main, U, global;

  global = this;

  Main = (function() {
    var ANIMATION_IMG_NUM;

    ANIMATION_IMG_NUM = 4;

    function Main() {
      U.phello();
      this.initCss();
      this.preloadImgs();
      this.startAnimation();
      return;
    }

    Main.prototype.initCss = function() {};

    Main.prototype.preloadImgs = function() {
      var i, _i, _results;
      _results = [];
      for (i = _i = 0; 0 <= ANIMATION_IMG_NUM ? _i < ANIMATION_IMG_NUM : _i > ANIMATION_IMG_NUM; i = 0 <= ANIMATION_IMG_NUM ? ++_i : --_i) {
        _results.push($('<img>').attr('src', "img/chara" + i + ".png"));
      }
      return _results;
    };

    Main.prototype.startAnimation = function() {
      var i, update;
      i = 0;
      update = function() {
        $('#main>img').attr('src', "img/chara" + i + ".png");
        i++;
        if (i === ANIMATION_IMG_NUM) {
          i = 0;
        }
      };
      setInterval(update, 100);
    };

    return Main;

  })();

  global.Util = {
    phello: function() {
      return console.log("hello");
    },
    randomInt: function(n) {
      return M.floor(M.random() * n);
    },
    generateRandomColor255: function(chroma) {
      var color_elem;
      if (chroma == null) {
        chroma = 255;
      }
      color_elem = [255, 255 - chroma, U.randomInt(255)].shuffle();
      return {
        r: color_elem[0],
        g: color_elem[1],
        b: color_elem[2]
      };
    }
  };

  Array.prototype.shuffle = function() {
    var buf;
    buf = [];
    while (this.length > 0) {
      buf.push(this.splice(U.randomInt(this.length), 1)[0]);
    }
    while (buf.length > 0) {
      this.push(buf.pop());
    }
    return this;
  };

  M = Math;

  U = Util;

  $(function() {
    return global.main = new Main;
  });

}).call(this);
